import { Chiot, Pet, Product } from "./types";

export const pets: Pet[] = [
  {
    id: "MO231",
    name: "Pomeranian White",
    image: "/image1.png",
    gender: "Male",
    age: "02 months",
    price: "6.900.000 VND",
  },
  {
    id: "MO502",
    name: "Poodle Tiny Yellow",
    image: "/image2.png",
    gender: "Female",
    age: "02 months",
    price: "3.900.000 VND",
  },
  {
    id: "MO102",
    name: "Poodle Tiny Sepia",
    image: "/image3.png",
    gender: "Male",
    age: "02 months",
    price: "4.000.000 VND",
  },
  {
    id: "MO512",
    name: "Alaskan Malamute Grey",
    image: "/image4.png",
    gender: "Male",
    age: "02 months",
    price: "8.900.000 VND",
  },
  {
    id: "MO231",
    name: "Pembroke Corgi Cream",
    image: "/image5.png",
    gender: "Female",
    age: "02 months",
    price: "7.900.000 VND",
  },
  {
    id: "MO502",
    name: "Pembroke Corgi Tricolor",
    image: "/image6.png",
    gender: "Male",
    age: "02 months",
    price: "9.000.000 VND",
  },
  {
    id: "MO231",
    name: "Pomeranian White",
    image: "/image7.png",
    gender: "Female",
    age: "02 months",
    price: "6.500.000 VND",
  },
  {
    id: "MO512",
    name: "Poodle Tiny Dairy Cow",
    image: "/image8.png",
    gender: "Male",
    age: "02 months",
    price: "5.000.000 VND",
  },
];

export const products: Product[] = [
  {
    image: "/imageProd1.png",
    name: "Reflex Plus Adult Cat Food Salmon",
    productType: "Product: Cat Food",
    details: "Size: 380gm",
    price: "140.000 VND",
    gift: "Free Toy & Free Shaker",
    giftType: "cat",
  },
  {
    image: "/imageProd2.png",
    name: "Reflex Plus Adult Cat Food Salmon",
    productType: "Product: Cat Food",
    details: "Size: 1.5kg",
    price: "1.100.000 VND",
    gift: "Free Toy & Free Shaker",
    giftType: "cat",
  },
  {
    image: "/imageProd3.png",
    name: "Cat scratching ball toy kitten sisal rope ball",
    productType: "Product: Toy",
    details: "",
    price: "410.000 VND",
    gift: "Free Cat Food",
    giftType: "cat",
  },
  {
    image: "/imageProd4.png",
    name: "Cute Pet Cat Warm Nest",
    productType: "Product: Toy",
    details: "",
    price: "410.000 VND",
    gift: "Free Cat Food",
    giftType: "cat",
  },
  {
    image: "/imageProd5.png",
    name: "NaturVet Dogs - Omega-Gold Plus Salmon Oil",
    productType: "Product: Dog Food",
    details: "Size: 380gm",
    price: "350.000 VND",
    gift: "Free Toy & Free Shaker",
    giftType: "dog",
  },
  {
    image: "/imageProd6.png",
    name: "Costumes Fashion Pet Clothes Cowboy Rider",
    productType: "Product: Costume",
    details: "Size: 1.5kg",
    price: "500.000 VND",
    gift: "Free Toy & Free Shaker",
    giftType: "dog",
  },
  {
    image: "/imageProd7.png",
    name: "Costumes Chicken drumsti cki Headband",
    productType: "Product: Costume",
    details: "",
    price: "400.000 VND",
    gift: "Free Cat Food",
    giftType: "cat",
  },
  {
    image: "/imageProd8.png",
    name: "Plush Pet Toy",
    productType: "Product: Toy",
    details: "",
    price: "250.000 VND",
    gift: "Free Food & Shaker",
    giftType: "cat",
  },
];

export const chiotsData: Chiot[] = [
  {
    id: 1,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 4500000,
    imageUrl: "/imgCte1.png",
  },
  {
    id: 2,
    nom: "HEMGE",
    race: "Poodle Toy",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3900000,
    imageUrl: "/imgCte2.png",
  },
  {
    id: 3,
    nom: "HEMGE",
    race: "Alaskan",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.2 kg",
    prix: 8900000,
    imageUrl: "/imgCte3.png",
  },
  {
    id: 4,
    nom: "HEMGE",
    race: "Bichon Frize",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte4.png",
  },
  {
    id: 5,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte5.png",
  },
  {
    id: 6,
    nom: "HEMGE",
    race: "Shiba Inu",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 3900000,
    imageUrl: "/imgCte6.png",
  },
  {
    id: 7,
    nom: "HEMGE",
    race: "Rottweiler",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.5 kg",
    prix: 4500000,
    imageUrl: "/imgCte7.png ",
  },
  {
    id: 8,
    nom: "HEMGE",
    race: "Golden Retriever",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.2 kg",
    prix: 3900000,
    imageUrl: "/imgCte8.png",
  },
  {
    id: 9,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.0 kg",
    prix: 8900000,
    imageUrl: "/imgCte9.png",
  },
  {
    id: 10,
    nom: "HEMGE",
    race: "Alaskan",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte10.png",
  },
  {
    id: 11,
    nom: "HEMGE",
    race: "Poodle Toy",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3900000,
    imageUrl: "/imgCte11.png",
  },
  {
    id: 12,
    nom: "HEMGE",
    race: "Shiba Inu",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.2 kg",
    prix: 3900000,
    imageUrl: "/imgCte12.png",
  },
  {
    id: 13,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.0 kg",
    prix: 3800000,
    imageUrl: "/imgCte13.png",
  },
  {
    id: 14,
    nom: "HEMGE",
    race: "Poodle Toy",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte14.png",
  },
  {
    id: 15,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte15.png",
  },
  {
    id: 16,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 17,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte16.png",
  },
  {
    id: 18,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte17.png",
  },
  {
    id: 19,
    nom: "HEMGE",
    race: "Alaskan",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 8900000,
    imageUrl: "/imgCte18.png",
  },
  {
    id: 20,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.2 kg",
    prix: 4500000,
    imageUrl: "/imgCte19.png",
  },
  {
    id: 21,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 22,
    nom: "HEMGE",
    race: "Poodle Toy",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte21.png",
  },
  {
    id: 23,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte22.png",
  },
  {
    id: 24,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte23.png",
  },
  {
    id: 25,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte24.png",
  },
  {
    id: 26,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte25.png",
  },
  {
    id: 27,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 28,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 29,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 30,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 31,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 32,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 33,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 34,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 35,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 36,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 37,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 38,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 39,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 40,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 41,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 42,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 43,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 44,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 45,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 46,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 47,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 48,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 49,
    nom: "HEMGE",
    race: "Pomeranian",
    sexe: "Mâle",
    age: "2 mois",
    poids: "0.9 kg",
    prix: 3800000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 50,
    nom: "HEMGE",
    race: "Maltese",
    sexe: "Femelle",
    age: "2 mois",
    poids: "0.8 kg",
    prix: 3900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 51,
    nom: "HEMGE",
    race: "Husky",
    sexe: "Mâle",
    age: "2 mois",
    poids: "1.3 kg",
    prix: 8900000,
    imageUrl: "/imgCte20.png",
  },
  {
    id: 52,
    nom: "HEMGE",
    race: "Corgi",
    sexe: "Femelle",
    age: "2 mois",
    poids: "1.1 kg",
    prix: 4500000,
    imageUrl: "/imgCte20.png",
  },
];
